language: go

go: 1.8

branches:
  except:
    - /^*-[0-9]/

install:
  - make install

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - |
    if [ -z "$TRAVIS_TAG" ]; then
      echo "Using TRAVIS_BUILD_NUMBER as revision..."
      export CLI_VERSION="${CLI_FEATURE_VERSION}.${TRAVIS_BUILD_NUMBER}";
    else
      echo "Using TRAVIS_TAG as revision..."
      export CLI_VERSION="${TRAVIS_TAG}"
    fi
  - TARGET_PLATFORM=darwin make release
  - TARGET_PLATFORM=linux make release

env:
  global:
    - CLI_FEATURE_VERSION=0.9
    - CLI_VERSION="${CLI_FEATURE_VERSION}.${TRAVIS_BUILD_NUMBER}"

# if this isnt a PR, and we're building the master branch *only*, then lets tag
# this version which will in turn trigger another build that the github release
# will be cut from.
before_deploy:
  - git tag ${CLI_VERSION} -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - export BODY=$(git log -1 --pretty='%s')

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "TvJoJIIPBaCe8QSJp2t+KlW4vy99ZxlWojUGOiftYHltgBQRr01YKC1/uFt8+vAUjaZQ1iTjjX7qkeA18SIExdHFQrj+WIMrNKfC7Kkox/wkCq+b8N3IH1rS6uj13n7pRr9HRBWNooNE/bR63AFCVeut/rJM/fep0vOCRd+vKAocxqhOQ9DHo9WruoL9buMriUhtE+PaIs+Yfbi6ejnCZKxeCMyNaoG5VDGWC/LJhnGQkPYKFUM2xDy8KukqrNnzJiLRUlo6/UO3x8p8Lv1v+hhRIu7aaapQN8D/72jTU/OVRIV8ro2qkhLZ21x9y1d/4naCmvzggGLYpmkCr4aUB0Om6pLFvVXtaCSQnR9423NyiC+U2fFJ647nwljIkxmJ9pYVF0lnjTp2GulSua3+Y+oCi/hk6Gq4rwIqDIBKcrHdPIh/vqUIuRcCsIsIPwX97DMNtyha+S9JJK1karNaQ2O313Vs0z/XSMcB2i2vUvZtQF247v3XqqIc3S2Iq/t+RGaM/xLdINEtvyS8vO+JWMEdqr/0RFNbUCXuaQIFBhm8MCrg+zqSisMBl5KQaaQBGy6tPiPQ8Xf6NaLdBeORHdHQf/tkB3n427XTt+ZcoUPx+qIhUj3B2vfFIghToriHheCjPYrJDIJuF1QlqsTncNr4baiPrGG2YdvBkMaYD3A="
  file_glob: true
  file: target/*
  body: ${BODY}
  on:
    repo: getnelson/cli
    branch: master
