language: go

install:
  - make install

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"

script:
  - export OUTPUT_NAME=`make -s tar`
  - make release
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then curl -u $NEXUS_CREDENTIALS --upload-file target/$OUTPUT_NAME $NEXUS_URL/$OUTPUT_NAME; fi"
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then echo 'Download from ' $NEXUS_URL/$OUTPUT_NAME; fi"

matrix:
  include:
    - go: 1.6
      env: TARGET_PLATFORM=linux
    - go: 1.6
      env: TARGET_PLATFORM=darwin

env:
  global:
    - CLI_FEATURE_VERSION=0.5
    - CLI_VERSION="${CLI_FEATURE_VERSION}.${TRAVIS_BUILD_NUMBER}"
    - NEXUS_URL="http://nexus.oncue.verizon.net/nexus/content/repositories/releases/verizon/inf/nelson/cli/$CLI_VERSION/"
    - secure: "A0l4p95hkHbFs1yWTaBAYp559bQen4Y8hdHYc/qAyu4b5DJJGEesYPSQctTCFFIKi94X8MCv2WNMf3qTwTZayP96mXh9SXS9tsTAIc2w8GqXgTxipMjq1BQxL4p0/Vy613CRqH1DvPZv8HmuEEl2MYEVRlhTnH9KM34qNQ4OwE0="
