language: go

go:
  - "1.6"

install:
  - go get github.com/constabulary/gb/...

script:
  - gb test -v
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 gb build # 64 bit linux
  - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 gb build # 64 bit OSX
