language: go

# go:
#   - "1.6"

install:
  - go get github.com/constabulary/gb/...

script:
  - gb test -v
  - GOOS=$TARGET_PLATFORM GOARCH=amd64 CGO_ENABLED=0 gb build
  - tar -zcvf nelson-$TARGET_PLATFORM-amd64-$CLI_VERSION.tar.gz bin/nelson-$TARGET_PLATFORM-amd64
  # - GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 gb build # 64 bit OSX
  # - tar -zcvf nelson-darwin-amd64-$CLI_VERSION.tar.gz bin/nelson-darwin-amd64

# after_success:
  # - curl -v -u $NEXUS_CREDENTIALS --upload-file nelson-linux-amd64-$TRAVIS_BUILD_NUMBER.tar.gz http://localhost:8081/nexus/content/repositories/releases/org/foo/1.0/foo-1.0.pom

matrix:
  include:
    - go: 1.6
      env:
        - CLI_VERSION="0.1.$TRAVIS_BUILD_NUMBER"
        - TARGET_PLATFORM=linux
        - NEXUS_BASE_URL="http://nexus.oncue.verizon.net/nexus/content/repositories/releases/verizon/inf/nelson/cli/$CLI_VERSION/"
    - go: 1.6
      env:
        - CLI_VERSION="0.1.$TRAVIS_BUILD_NUMBER"
        - TARGET_PLATFORM=darwin
        - NEXUS_BASE_URL="http://nexus.oncue.verizon.net/nexus/content/repositories/releases/verizon/inf/nelson/cli/$CLI_VERSION/"

# env:
#   global:
#     - secure: "A0l4p95hkHbFs1yWTaBAYp559bQen4Y8hdHYc/qAyu4b5DJJGEesYPSQctTCFFIKi94X8MCv2WNMf3qTwTZayP96mXh9SXS9tsTAIc2w8GqXgTxipMjq1BQxL4p0/Vy613CRqH1DvPZv8HmuEEl2MYEVRlhTnH9KM34qNQ4OwE0="
